Adicionar o tipo Entities
dev-senior-com-br/seniorx-http-camel-api pull request #1
Opened 2022-03-31 20:00 UTC by leonardocardososenior

Adicionar o tipo Entities para poder realizar uma request para as entidades de faixada do SeniorX

2022-04-01 10:21 UTC, betonetotbo approved these changes
ok.

2022-04-01 10:32 UTC, emersonkopp requested changes

2022-04-01 10:32 UTC, emersonkopp commented on src/main/java/br/com/senior/seniorx/http/camel/PrimitiveType.java
> +    ENTITIES("entities"); //
Alterar para ENTITY("entities"), seguindo o padrão dos outros tipos.

2022-04-03 23:37 UTC, leonardocardososenior commented
@emersonkopp e @betonetotbo realizei o ajuste no nome do ENUM como solicitado.

2022-04-04 11:05 UTC, merged

2022-04-04 11:41 UTC, emersonkopp commented
@leonardocardososenior liberada a versão 1.1.0 da biblioteca com a alteração.